apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-{{ .Values.global.environment }}
  labels:
    app: {{ .Values.api.name }}
    env: {{ .Values.global.environment }}
    {{- include "acme-stack.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.api.name }}
    env: {{ .Values.global.environment }}
  ports:
    {{- range .Values.api.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  type: {{ .Values.api.service.type }}