version: '3.8'

services:
  # Control Core PAP API
  cc-pap-api:
    build:
      context: ../../cc-pap-api
      dockerfile: Dockerfile
    container_name: cc-pap-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@cc-db:5432/control_core_db
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    depends_on:
      - cc-db
    networks:
      - controlcore-network
    restart: unless-stopped

  # Control Core Database
  cc-db:
    image: postgres:15
    container_name: cc-db
    environment:
      - POSTGRES_DB=control_core_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - cc_postgres_data:/var/lib/postgresql/data
    networks:
      - controlcore-network
    restart: unless-stopped

  # Control Core Frontend (Policy Admin UI)
  cc-frontend:
    build:
      context: ../../cc-pap
      dockerfile: Dockerfile
    container_name: cc-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    depends_on:
      - cc-pap-api
    networks:
      - controlcore-network
    restart: unless-stopped

  # Control Core Bouncer (PEP)
  cc-bouncer:
    build:
      context: ../../cc-bouncer
      dockerfile: Dockerfile
    container_name: cc-bouncer
    ports:
      - "8080:8080"
    environment:
      - BOUNCER_PORT=8080
      - TARGET_HOST=localhost:8000
      - PAP_API_URL=http://cc-pap-api:8000
      - OPAL_SERVER_URL=http://cc-opal:7000
      - TENANT_ID=${TENANT_ID}
      - API_KEY=${API_KEY}
      - LOG_ENABLED=true
      - CACHE_ENABLED=true
    depends_on:
      - cc-pap-api
      - cc-opal
    networks:
      - controlcore-network
    restart: unless-stopped

  # OPAL Server for Policy Synchronization
  cc-opal:
    image: permitio/opal-server:latest
    container_name: cc-opal
    ports:
      - "7000:7000"
    environment:
      - OPAL_POLICY_REPO_URL=${OPAL_POLICY_REPO_URL}
      - OPAL_DATA_SOURCES_CONFIG=./config/data-sources.json
      - PAP_API_URL=http://cc-pap-api:8000
    networks:
      - controlcore-network
    restart: unless-stopped

  # Demo App API (for testing)
  acme-demo-api:
    build: ../../acme-consulting-demo-api
    container_name: acme-demo-api
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@acme-db:5432/acme_demo_db
    depends_on:
      - acme-db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - controlcore-network
    restart: unless-stopped

  # Demo App Database
  acme-db:
    image: postgres:15
    container_name: acme-db
    environment:
      - POSTGRES_DB=acme_demo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${ACME_POSTGRES_PASSWORD}
    volumes:
      - acme_postgres_data:/var/lib/postgresql/data
    networks:
      - controlcore-network
    restart: unless-stopped

  # Demo App Frontend
  acme-demo-frontend:
    build:
      context: ../../acme-consulting-demo-frontend
      dockerfile: Dockerfile
    container_name: acme-demo-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://acme-demo-api:8000
    depends_on:
      - acme-demo-api
    networks:
      - controlcore-network
    restart: unless-stopped

networks:
  controlcore-network:
    driver: bridge

volumes:
  cc_postgres_data:
  acme_postgres_data:
