version: '3.8'

services:
  api:
    build:
      context: ../acme-consulting-demo-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/consulting_db
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=consulting_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ../acme-consulting-demo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: