apiVersion: v2
name: cc-demoapp
description: A Helm chart for Control Core Demo App stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
